-- Cosmii DB Schema for Supabase
-- Run this in the Supabase SQL Editor

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- ══════════════════════════════════════════
-- Books (admin-managed)
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS books (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT DEFAULT '',
  cover_url TEXT,
  color TEXT DEFAULT '#6366f1',
  total_chunks INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ══════════════════════════════════════════
-- Chunks (book text + embeddings)
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS chunks (
  id TEXT PRIMARY KEY,
  book_id TEXT REFERENCES books(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  chapter TEXT DEFAULT '',
  page_num TEXT DEFAULT '',
  embedding VECTOR(1536)
);

CREATE INDEX IF NOT EXISTS idx_chunks_book ON chunks(book_id);
CREATE INDEX IF NOT EXISTS idx_chunks_embedding ON chunks
  USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- ══════════════════════════════════════════
-- Lessons (pre-generated by LLM)
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS lessons (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  book_id TEXT REFERENCES books(id) ON DELETE CASCADE,
  order_index INT NOT NULL DEFAULT 0,
  title TEXT DEFAULT '',
  lesson_type TEXT DEFAULT 'dialogue',
  content_json JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_lessons_book ON lessons(book_id);

-- ══════════════════════════════════════════
-- Quizzes (linked to lessons)
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS quizzes (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  lesson_id TEXT REFERENCES lessons(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  options_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  correct_index INT NOT NULL DEFAULT 0,
  explanation TEXT DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_quizzes_lesson ON quizzes(lesson_id);

-- ══════════════════════════════════════════
-- User Progress
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS user_progress (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  user_id TEXT NOT NULL,
  lesson_id TEXT REFERENCES lessons(id) ON DELETE CASCADE,
  completed BOOLEAN DEFAULT FALSE,
  score INT,
  review_needed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  UNIQUE(user_id, lesson_id)
);

CREATE INDEX IF NOT EXISTS idx_progress_user ON user_progress(user_id);

-- ══════════════════════════════════════════
-- User Stats (XP, streak, level)
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS user_stats (
  user_id TEXT PRIMARY KEY,
  xp INT DEFAULT 0,
  streak_days INT DEFAULT 0,
  last_study_date DATE,
  level INT DEFAULT 1
);

-- ══════════════════════════════════════════
-- Vector search RPC function
-- ══════════════════════════════════════════
CREATE OR REPLACE FUNCTION match_chunks(
  query_embedding VECTOR(1536),
  match_count INT DEFAULT 8,
  filter_book_id TEXT DEFAULT NULL
)
RETURNS TABLE (
  id TEXT,
  book_id TEXT,
  content TEXT,
  chapter TEXT,
  page_num TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    c.id,
    c.book_id,
    c.content,
    c.chapter,
    c.page_num,
    1 - (c.embedding <=> query_embedding) AS similarity
  FROM chunks c
  WHERE (filter_book_id IS NULL OR c.book_id = filter_book_id)
  ORDER BY c.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;
